# Generated by Django 3.2.5 on 2025-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0007_auto_20250728_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('family_friends', 'Family & Friends'), ('work', 'Work')], default='family_friends', max_length=20),
        ),
    ]
