# Generated by Django 3.2.5 on 2025-09-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0013_auto_20250904_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('work', 'Work')], default='family_friends', max_length=20),
        ),
    ]
